name: penguins_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - mlflow=2.5.0
  - pip
  - pip:
    - seaborn==0.12.2