name: MLflow Model Training CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==1.5.3 numpy==1.24.3 scikit-learn==1.3.0 mlflow==2.5.0 seaborn==0.12.2
    
    - name: Run MLflow project
      run: |
        cd MLproject
        python modelling.py
    
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLproject/mlruns/
        retention-days: 30
